### PR TITLE
Avoid rewriting read-only methods in strict mode

### PR DESCRIPTION
**Pull request by jonathansp**
If `runInContext` method is called more than once with same context, a `TypeError` is raised since we're trying to rewrite `window` globals.

``` javascript
let sandbox = vm.createContext({});

while (someloop)
    vm.runInContext('code...', sandbox);
```

_Uncaught TypeError: Cannot assign to read only property 'Infinity' of object '[object Window]'_

### CODE REVIEW

**Comment by jonathansp** [comment]
@substack, may you check this PR?

**Comment by jonathansp** [comment]
@substack any news?

**Comment by jonathansp** [comment]
?

**Comment by derhuerst** [comment]
bump. (:

**Comment by jonathansp** [comment]
:eyes:

**Comment by jonathansp** [comment]
happy 2019!

**Comment by jonathansp** [comment]
seems like the project is dead. Closing the issue.

**Pull request closed without merging**
